Add to cart Functionality
h2grover/qa-automation-sample pull request #7
Opened 2021-10-13 10:35 UTC by Shrey1508

2021-11-02 05:23 UTC, hrk15 commented on .env
> +HEADLESS = false
@Shrey1508 Let's maintain consistency remove spaces from here.

2021-11-02 05:23 UTC, hrk15 commented on Amazon.js
> +HEIGHT = Number(HEIGHT);
@Shrey1508 why are we doing this globally when we are using this at one place in one method. we can do this in the method itself. Also `const bool = HEADLESS === 'true';` is not the right way. If someone sets `HEADLESS` value to `abc` it will set bool to `false`. we don't want that it should return error in that case. Please look for a better option to parse.

2021-11-02 05:23 UTC, hrk15 commented on Amazon.js
> +	await page.waitForTimeout(3000);
@Shrey1508 Please remove the wait and find a better way.

2021-11-02 05:23 UTC, hrk15 commented on Amazon.js
> +		await homepage.mainProduct(page);
@Shrey1508 Why are we passing `page` object in every method their is a better way to do it via constructor of page classes. Please use that.

2021-11-02 05:23 UTC, hrk15 commented on Amazon.js
> +		await page.click(addToCart.crtbtn);
@Shrey1508 Let's maintain consistency since you are following the `POM` way use it everywhere and don't call the `page` methods directly from test specs.

2021-11-02 05:23 UTC, hrk15 commented on Amazon.js
> +			await page.waitForTimeout(2000);
@Shrey1508 Please try to perform this without wait. `2 sec` wait in a loop can increase the execution time a lot.

2021-11-02 05:23 UTC, hrk15 commented on Homepage.js
> +		const random = Math.floor(Math.random() * (product.length - 1));
@Shrey1508 Let's create a `utility` file and keeps methods like getting random number in it and use it as per requirement.

2021-11-02 05:23 UTC, hrk15 commented on Homepage.js
> +		await page.waitForTimeout(2000);
@Shrey1508 Avoid using sleeps and find better way to use wait class. Sleep should be you last option. It is not a recommended way.

2021-11-02 05:23 UTC, hrk15 commented on locators.js
> +const login = {
@Shrey1508 Let's keep the selectors in the respective pages where they belong rather than creating a new file.

2021-11-02 05:24 UTC, hrk15 requested changes
@Shrey1508 I have requested some changes please go through it.

2021-11-05 07:48 UTC, hrk15 commented on .env
> +USER_NAME=9639385816
@Shrey1508 Remove this file. Please beware about this you should not publish `.env` on git you credentials are visible.

2021-11-05 07:48 UTC, hrk15 commented on Amazon.js
> +const bool = HEADLESS === 'true';
@Shrey1508 Still not addressed. Please look at the previous comment regarding this.

2021-11-05 07:48 UTC, hrk15 commented on Amazon.js
> +	let text = await page.$eval(addToCart.cart, (element) => element.textContent);
@Shrey1508 Let's follow POM and make this a method in the respective page it belongs to and only use it by calling that particular method.

2021-11-05 07:48 UTC, hrk15 commented on Amazon.js
> +		let text = await page.$eval(addToCart.cart, (element) => element.textContent);
@Shrey1508 Let's follow POM and make this a method in the respective page it belongs to and only use it by calling that particular method.

2021-11-05 07:48 UTC, hrk15 commented on Amazon.js
> +	//browser.close();
@Shrey1508 Why is this line commented?

2021-11-05 07:48 UTC, hrk15 commented on Homepage.js
> +		const fr = await utility.getrandomfinal(finalproduct);
@Shrey1508 Please use proper variable names which looks meaningful and makes code more readable.

2021-11-05 07:48 UTC, hrk15 commented on Utility.js
> +	async getrandom(product) {
@Shrey1508 Use camel casing you can find about it on google. Follow the camel casing in naming functions and variables everywhere.

2021-11-05 07:48 UTC, hrk15 requested changes
@Shrey1508 I have requested more changes.

2021-11-05 07:49 UTC, hrk15 commented on Amazon.js
> +HEIGHT = Number(HEIGHT);
@Shrey1508 The bool logic is still not addressed please look into it.

2021-11-08 13:08 UTC, Shrey1508 commented
have done with all the requested changes. Kindly have a look

2021-11-09 04:37 UTC, hrk15 commented on Amazon.js
> +});
@Shrey1508 will it be able to handle `True`, `False`, `TRUE`, `FALSE`. If not please update the logic. You can use `JSON` library here too rather than doing all this.

2021-11-09 04:38 UTC, hrk15 commented on Amazon.js
>  			height: Number(HEIGHT)
@Shrey1508 why are we using `Number` instead of `parseInt` what is the advantage?

2021-11-09 04:49 UTC, hrk15 commented on Amazon.js
> +		expect(productsInCart).to.be.equal(0 && 1);
@Shrey1508 why `0 & 1`?

2021-11-09 04:49 UTC, hrk15 requested changes

2021-11-09 04:49 UTC, hrk15 commented on sample.env
> +HEADLESS = false
@Shrey1508 remove spaces here.

2021-11-09 04:49 UTC, hrk15 commented on Utility.js
> +	}
@Shrey1508 let's create one function for random with min and max values as parameters in order to avoid creating multiple methods.

2021-11-09 04:49 UTC, hrk15 commented on Homepage.js
> +var utility = new Utility();
@Shrey1508 study about where to use `var`, `const` and `let` and use the one which suites here the best.

2021-11-09 04:49 UTC, hrk15 commented on Amazon.js
> +		await homepage.mainProduct();
@Shrey1508 I don't see any assertion step to verify that the cart is nit empty after addition of products.

2021-11-09 05:34 UTC, Shrey1508 commented on Amazon.js
> +		expect(productsInCart).to.be.equal(0 && 1);
it is actually 0......I am just checking the condition so forgot to remove 1

2021-11-09 06:24 UTC, Shrey1508 commented on Amazon.js
>  			height: Number(HEIGHT)
Number() converts the type whereas parseInt parses the value of input.
Since, in height and width , we always have to provide a digit character not a non -digit character . So, we don't need parseInt here

2021-11-10 06:05 UTC, hrk15 commented on Amazon.js
>  			height: Number(HEIGHT)
@Shrey1508 While doing some research i found this 
![image](https://user-images.githubusercontent.com/21085019/141058401-70b03b88-6780-47d5-9785-32de6934cb2a.png)
https://thisthat.dev/number-constructor-vs-parse-int/

What do you think will be best suited in our use case and why?

2021-11-10 06:05 UTC, hrk15 requested changes

2021-11-10 06:05 UTC, hrk15 commented on Homepage.js
> +let utility = new Utility();
@Shrey1508 Why you used `let` here instead of `var` or `const`?

2021-11-10 06:16 UTC, hrk15 commented on Amazon.js
> +		for (i = 0; i < productsInCart; i++) {
@Shrey1508 Instead of `i` use names like `product` or something else which make code more readable and look meaningful.

2021-11-10 06:16 UTC, hrk15 requested changes

2021-11-10 06:16 UTC, hrk15 commented on Amazon.js
> +	expect(productsInCart).to.be.greaterThan(0);
@Shrey1508 How many products are we adding let's match that number.

2021-11-10 06:16 UTC, hrk15 commented on Homepage.js
> +		product = await this.page.$$(addToCart.productlinks);
@Shrey1508 what variable is `product` var, let or const and where is it declared?

2021-11-10 06:16 UTC, hrk15 commented on Homepage.js
> +		product = await this.page.$$(addToCart.finalproductlinks);
@Shrey1508 what variable is `product` var, let or const and where is it declared?

2021-11-10 07:00 UTC, Shrey1508 commented on Amazon.js
> +	expect(productsInCart).to.be.greaterThan(0);
we have to add assertion step that cart shouldn't be empty thats why i did this.
We are adding only one product ...we can check for that cart value also

2021-11-10 07:03 UTC, Shrey1508 commented on Homepage.js
> +		product = await this.page.$$(addToCart.productlinks);
it is declared globally where you are asking why we are using let instead of var and const....and also product is using in many methods thats why we have to declare it globally

2021-11-10 07:03 UTC, Shrey1508 commented on Homepage.js
> +		product = await this.page.$$(addToCart.finalproductlinks);
it is declared globally where you are asking why we are using let instead of var and const....and also product is using in many methods thats why we have to declare it globally

2021-11-10 07:06 UTC, Shrey1508 commented on Amazon.js
> +		for (i = 0; i < productsInCart; i++) {
its just a simple deletion loop

2021-11-10 07:37 UTC, Shrey1508 commented on Homepage.js
> +let utility = new Utility();
we cannot used const here as the value of product is changing as It is not fixed

2021-11-11 04:42 UTC, hrk15 commented on Amazon.js
>  			height: Number(HEIGHT)
@Shrey1508 Not answered yet.

2021-11-11 04:43 UTC, hrk15 requested changes

2021-11-11 04:43 UTC, hrk15 commented on Homepage.js
> +let utility = new Utility();
@Shrey1508 The comment is on line 19 why are you answering about the product. Also declare product locally in the function as its value is changing and the changed value is only limited to that particular method.

2021-11-11 06:44 UTC, hrk15 commented
@Shrey1508 Resolve the conflicts in this PR and made the requested changes.

2021-11-11 12:21 UTC, merged